# Generated by Django 2.2.3 on 2019-08-08 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
        ('spiderfarm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='spiderfarm.Domain')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('imported', 'Imported'), ('active', 'Active'), ('stalled', 'Stalled'), ('sold', 'Sold'), ('renewed', 'Renewed'), ('dead', 'Dead'), ('closed', 'Closed')], default='imported', max_length=255, null=True, verbose_name='Status of Lead')),
                ('quality', models.CharField(blank=True, choices=[('solid', 'Solid'), ('shallow', 'Shallow'), ('split', 'Split')], max_length=255, null=True, verbose_name='Quality of Lead')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('assigned_to', models.ManyToManyField(blank=True, null=True, related_name='lead_assigned_users', to=settings.AUTH_USER_MODEL)),
                ('teams', models.ManyToManyField(blank=True, null=True, to='teams.Teams')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
