# Generated by Django 2.2.3 on 2019-09-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderfarm', '0003_auto_20190906_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='import_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SSL', 'SSL')], default='NEW', max_length=25, verbose_name='Guaranteed minimum scrape'),
        ),
    ]
