# Generated by Django 2.2.3 on 2019-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderfarm', '0004_domain_import_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='import_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('SSL', 'SSL')], default='NEW', max_length=25, verbose_name='Import status'),
        ),
    ]
