# Generated by Django 2.2.3 on 2019-09-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderfarm', '0005_auto_20190907_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='mx_servers',
        ),
        migrations.AddField(
            model_name='domain',
            name='mx_servers',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='MX servers'),
        ),
        migrations.RemoveField(
            model_name='domain',
            name='name_servers',
        ),
        migrations.AddField(
            model_name='domain',
            name='name_servers',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Name servers'),
        ),
        migrations.RemoveField(
            model_name='domain',
            name='ssl_san',
        ),
        migrations.AddField(
            model_name='domain',
            name='ssl_san',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SAN list'),
        ),
    ]
