# Generated by Django 2.2.3 on 2019-09-20 01:24

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('spiderfarm', '0007_auto_20190919_0124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='ssl_san',
        ),
        migrations.AddField(
            model_name='domain',
            name='ssl_san',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='spiderfarm.TaggedSanEntries', to='spiderfarm.SanListTag', verbose_name='SAN List'),
        ),
    ]
