# Generated by Django 2.2.3 on 2019-09-20 02:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('spiderfarm', '0008_auto_20190919_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='name_servers',
        ),
        migrations.AddField(
            model_name='domain',
            name='name_servers',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='spiderfarm.TaggedNameServers', to='spiderfarm.NameServerTag', verbose_name='Name servers'),
        ),
    ]
