# Generated by Django 2.2.3 on 2019-10-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderfarm', '0010_auto_20190929_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='ssl_issuer_org_unit',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Issuer org unit'),
        ),
    ]
