# Generated by Django 2.2.3 on 2019-10-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderfarm', '0012_auto_20191013_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='last_ghost_crawl',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Ghost crawl'),
        ),
    ]
