# Generated by Django 2.2.3 on 2019-10-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderfarm', '0013_domain_last_ghost_crawl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedzonefragmentstag',
            options={'verbose_name': 'Assigned Zone Fragments'},
        ),
        migrations.AlterModelOptions(
            name='certissuertag',
            options={'verbose_name': 'Certificate Issuer', 'verbose_name_plural': 'Certificate Issuers'},
        ),
        migrations.AlterModelOptions(
            name='mxservertag',
            options={'verbose_name': 'MX Server', 'verbose_name_plural': 'MX Servers'},
        ),
        migrations.AlterModelOptions(
            name='nameservertag',
            options={'verbose_name': 'Name Server', 'verbose_name_plural': 'Name Servers'},
        ),
        migrations.AlterModelOptions(
            name='sanlisttag',
            options={'verbose_name': 'SAN List'},
        ),
        migrations.AlterModelOptions(
            name='webservertag',
            options={'verbose_name': 'Web Server'},
        ),
        migrations.AlterModelOptions(
            name='xpoweredbytag',
            options={'verbose_name': 'X-Powered-By Header', 'verbose_name_plural': 'X-Powered-By Headers'},
        ),
    ]
