# Generated by Django 2.2.3 on 2019-10-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190808_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('USER', 'USER'), ('SALES', 'SALES'), ('SALES MANAGER', 'SALES MANAGER'), ('SALES ADMIN', 'SALES ADMIN')], max_length=50),
        ),
    ]
