# Generated by Django 2.2.3 on 2019-08-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20190808_0259'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_leads', to='leads.Lead'),
        ),
        migrations.AddField(
            model_name='account',
            name='tags',
            field=models.ManyToManyField(blank=True, to='accounts.Tags'),
        ),
    ]
