# Generated by Django 2.2.3 on 2019-08-08 09:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(blank=True, max_length=5, null=True)),
                ('reminder_time', models.IntegerField(blank=True, null=True, verbose_name='Reminder')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Event')),
                ('event_type', models.CharField(max_length=7, verbose_name='Type of the event')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Planned', 'Planned'), ('Held', 'Held'), ('Not Held', 'Not Held'), ('Not Started', 'Not Started'), ('Started', 'Started'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Deferred', 'Deferred')], max_length=64, verbose_name='Status')),
                ('direction', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(default=None)),
                ('close_date', models.DateField(default=None, null=True)),
                ('duration', models.IntegerField(default=None, null=True, verbose_name='Durations')),
                ('priority', models.CharField(blank=True, max_length=10)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='event_assigned_users', to=settings.AUTH_USER_MODEL)),
                ('attendees_contacts', models.ManyToManyField(blank=True, related_name='attendees_contact', to='contacts.Contact')),
            ],
        ),
    ]
